package edu.uptc.Modelo;

public enum Programa {
	INGENIERIA_SISTEMAS,
	INGENIERIA_GEOLÓGICA,
	INGENIERIA_MINAS,
	INGENIERIA_INDUSTRIAL,
	ADMINISTRACIÓN_EMPRESAS,
	CONTADURÍA,
	INGENIERIA_ELECTRÓNICA
}
